apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: chat-service
  namespace: chatbot
spec:
  replicas: 1
  strategy:
    blueGreen:
      activeService: chat-service
      previewService: chat-service-preview
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: 465776424604.dkr.ecr.us-east-1.amazonaws.com/student-support/chat-service:qa-v0.0.2
          ports:
            - containerPort: 8081  # Updated to match application port
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: production
spec:
  selector:
    app: chat-service
  ports:
    - port: 8081  # Updated to match application port
      targetPort: 8081
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service-preview
  namespace: production
spec:
  selector:
    app: chat-service
  ports:
    - port: 8081  # Updated to match application port
      targetPort: 8081
  type: ClusterIP
