apiVersion: argoproj.io/v1alpha1
kind: Deployment
metadata:
  name: university-chatbot-ui
  namespace: chatbot
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: university-chatbot-ui-active
      previewService: university-chatbot-ui-preview
  selector:
    matchLabels:
      app: university-chatbot-ui
  template:
    metadata:
      labels:
        app: university-chatbot-ui
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-10-0-3-151.ec2.internal
        subnet-type: private
      containers:
        - name: university-chatbot-ui
          image: 465776424604.dkr.ecr.us-east-1.amazonaws.com/student-support/university-chatbot-ui:qa-v2.0.0
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: university-chatbot-ui-active
  namespace: production
spec:
  selector:
    app: university-chatbot-ui
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: university-chatbot-ui-preview
  namespace: production
spec:
  selector:
    app: university-chatbot-ui
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP 