# dev-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-dev
spec:
  project: default
  source:
    repoURL: https://github.com/zmehta2/infra-repo.git
    targetRevision: main         # <- dev branch
    path: kubernetes/overlays/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: dev          # same namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true