apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zmehta2/infra-repo.git
    targetRevision: main         # <--- this is the stage branch
    path: kubernetes/overlays/uat
  destination:
    server: https://kubernetes.default.svc
    namespace: chatbot            # same namespace as dev/prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true