apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: faq-service
  namespace: production
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: faq-service
      previewService: faq-service-preview
  selector:
    matchLabels:
      app: faq-service
  template:
    metadata:
      labels:
        app: faq-service
    spec:
      containers:
        - name: faq-service
          image: 465776424604.dkr.ecr.us-east-1.amazonaws.com/student-support/faq-service:c1376203a1de118f815dde560fd2d99e5f50ecbd
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: faq-service
  namespace: production
spec:
  selector:
    app: faq-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: faq-service-preview
  namespace: production
spec:
  selector:
    app: faq-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP