# Convert from Deployment to Rollout
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: university-chatbot-ui
  namespace: production
spec:
  replicas: 1
  strategy:
    blueGreen:
      activeService: university-chatbot-ui-active
      previewService: university-chatbot-ui-preview
      autoPromotionSeconds: 60
  selector:
    matchLabels:
      app: university-chatbot-ui
  template:
    metadata:
      labels:
        app: university-chatbot-ui
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"  # Ensures Istio handles probes correctly
    spec:
      containers:
        - name: university-chatbot-ui
          image: 465776424604.dkr.ecr.us-east-1.amazonaws.com/student-support/university-chatbot-ui:v2.0.0
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: university-chatbot-ui-active
  namespace: production
spec:
  selector:
    app: university-chatbot-ui
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: university-chatbot-ui-preview
  namespace: production
spec:
  selector:
    app: university-chatbot-ui
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP