apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: university-chatbot-ui
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: university-chatbot-ui
  template:
    metadata:
      labels:
        app: university-chatbot-ui
    spec:
      containers:
        - name: university-chatbot-ui
          image: 465776424604.dkr.ecr.us-east-1.amazonaws.com/student-support/university-chatbot-ui:e632a6165230c4493e5569589cc1efb448071023
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
  strategy:
    blueGreen:
      activeService: university-chatbot-ui-active
      previewService: university-chatbot-ui-preview